<?php

namespace Database\Seeders;

use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();
        DB::table('items')->insert([
            [
                'category_id' => 1,
                'nama' => 'Beras SPHP 1 Kg',
                'deskripsi' => 'Beras SPHP 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Pangkuh/ IR.64/.IR.42 1 Kg',
                'deskripsi' => 'Beras Pangkuh/ IR.64/.IR.42 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Siam 1 Kg',
                'deskripsi' => 'Beras Siam 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Karang Dukuh 1 Kg',
                'deskripsi' => 'Beras Karang Dukuh 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Mayang 1 Kg',
                'deskripsi' => 'Beras Mayang 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Mangkok 1 Kg',
                'deskripsi' => 'Beras Mangkok 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Lahap 5 Kg',
                'deskripsi' => 'Beras Lahap 5 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'nama' => 'Beras Sania 5 Kg',
                'deskripsi' => 'Beras Sania 5 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'nama' => 'Gula Pasir 1 Kg',
                'deskripsi' => 'Gula Pasir 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Bimoli 1 Liter',
                'deskripsi' => 'Minyak Goreng Bimoli 1 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Sun Co 1 Liter',
                'deskripsi' => 'Minyak Goreng Sun Co 1 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Tropical 1 Liter',
                'deskripsi' => 'Minyak Goreng Tropical 1 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Sania 2 Liter',
                'deskripsi' => 'Minyak Goreng Sania 2 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Fortune 1 Liter',
                'deskripsi' => 'Minyak Goreng Fortune 1 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Kita 1 Liter',
                'deskripsi' => 'Minyak Goreng Kita 1 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'nama' => 'Minyak Goreng Curah 1 Liter',
                'deskripsi' => 'Minyak Goreng Curah 1 Liter',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'nama' => 'Tepung Segitiga Biru 1 Kg',
                'deskripsi' => 'Tepung Segitiga Biru 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 4,
                'nama' => 'Tepung Rose Brand 1 Kg',
                'deskripsi' => 'Tepung Rose Brand 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'nama' => 'Daging Sapi 1 Kg',
                'deskripsi' => 'Daging Sapi 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'nama' => 'Daging Sapi Paha Belakang 1 Kg',
                'deskripsi' => 'Daging Sapi Paha Belakang 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'nama' => 'Daging Sapi Tetelan 1 Kg',
                'deskripsi' => 'Daging Sapi Tetelan 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'nama' => 'Daging Ayam Broiler 1 Kg',
                'deskripsi' => 'Daging Ayam Broiler 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 5,
                'nama' => 'Daging Ayam Kampung 1 Kg',
                'deskripsi' => 'Daging Ayam Kampung 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 6,
                'nama' => 'Telur Ayam Broiler 1 Kg',
                'deskripsi' => 'Telur Ayam Broiler 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 6,
                'nama' => 'Telur Ayam Kampung 1 Kg',
                'deskripsi' => 'Telur Ayam Kampung 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 7,
                'nama' => 'Cabai Keriting 1 Kg',
                'deskripsi' => 'Cabai Keriting 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 7,
                'nama' => 'Cabai Biasa 1 Kg',
                'deskripsi' => 'Cabai Biasa 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 7,
                'nama' => 'Cabai Rawit Hijau 1 Kg',
                'deskripsi' => 'Cabai Rawit Hijau 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 7,
                'nama' => 'Cabai Rawit Merah 1 Kg',
                'deskripsi' => 'Cabai Rawit Merah 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 8,
                'nama' => 'Bawang Merah 1 Kg',
                'deskripsi' => 'Bawang Merah 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 8,
                'nama' => 'Bawang Putih 1 Kg',
                'deskripsi' => 'Bawang Putih 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 8,
                'nama' => 'Bawang Bombay 1 Kg',
                'deskripsi' => 'Bawang Bombay 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 9,
                'nama' => 'Kental Manis 1 Klg',
                'deskripsi' => 'Kental Manis 1 Klg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 9,
                'nama' => 'Susu Bubuk 1 Klg',
                'deskripsi' => 'Susu Bubuk 1 Klg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 10,
                'nama' => 'Garam Halus 1 Bks',
                'deskripsi' => 'Garam Halus 1 Bks',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 11,
                'nama' => 'Kacang Kedelai 1 Kg',
                'deskripsi' => 'Kacang Kedelai 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 11,
                'nama' => 'Kacang Hijau Impor 1 Kg',
                'deskripsi' => 'Kacang Hijau Impor 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 11,
                'nama' => 'Kacang Tanah 1 Kg',
                'deskripsi' => 'Kacang Tanah 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 12,
                'nama' => 'Mie Instant 1 Bks',
                'deskripsi' => 'Mie Instant 1 Bks',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Ketela Pohon 1 Kg',
                'deskripsi' => 'Ketela Pohon 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Tomat 1 Kg',
                'deskripsi' => 'Tomat 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Kentang Sedang 1 Kg',
                'deskripsi' => 'Kentang Sedang 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Sawi Hijau 1 Kg',
                'deskripsi' => 'Sawi Hijau 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Kangkung 1 Kg',
                'deskripsi' => 'Kangkung 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Ketimun Sedang 1 Kg',
                'deskripsi' => 'Ketimun Sedang 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Kacang Panjang 1 Kg',
                'deskripsi' => 'Kacang Panjang 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Tahu 1 Kg',
                'deskripsi' => 'Tahu 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Tempe 1 Kg',
                'deskripsi' => 'Tempe 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Pisang 1 Kg',
                'deskripsi' => 'Pisang 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 13,
                'nama' => 'Jeruk Lokal 1 Kg',
                'deskripsi' => 'Jeruk Lokal 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 14,
                'nama' => 'Ikan Gabus 1 Kg',
                'deskripsi' => 'Ikan Gabus 1 Kg',
                'hargaaverage' => 0,
                'tglharga' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        // for ($i = 0; $i < 4; ++$i) {
        //     DB::table('items')->insert([
        //         [
        //             // 'category_id' => Category::all()->random()->id,
        //             'nama' => 'Minyak Goreng Filma ' . Category::all()->random()->id,
        //             'deskripsi' => 'Minyak Goreng Filma ' . $faker->word(),
        //             'hargaaverage' => 0,
        //             'tglharga' => Carbon::now(),
        //             'created_at' => Carbon::now(),
        //             'updated_at' => Carbon::now(),
        //         ]
        //     ]);
        // }
    }
}
